language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t bumbleeshot/docker-kub -f Dockerfile.dev .

script:
  - docker run -e CI=true bumbleeshot/docker-kub npm run test