version: '3'

services:
  web:
    build: 
      # Where we want all the files for this image to be from.
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes: 
      - /app/node_modules
      - .:/app
  tests:
    build: 
      # Where we want all the files for this image to be from.
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
    
